spring:
  application:
    name: ticket-reservation-service-local
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://master.qa.ononay:8023

server:
  port: 4568
  tomcat:
    max-threads: 5

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
  endpoint:
    info:
      enabled: true
    health:
      enabled: false
  security:
    enabled: false

info:
  status: OK
  version: ${VERSION:1}
  env: local

payment-configuration:
  mongo-db-connection-string: mongodb://mongodb:27017/PaymentDB
  mongo-db-name: "PaymentDB"
  mongo-collection-name: "Payment"

flight-management-service:
  url: http://flightmanagementservice:4567
